# Generated by Django 2.2.5 on 2020-06-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumni_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.DateField()),
                ('company', models.CharField(max_length=256)),
                ('profile', models.CharField(max_length=256)),
                ('sector', models.CharField(max_length=256)),
                ('program', models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.Des', 'Bachelor of Design'), ('M.Tech', 'Master of Technology'), ('M.Des', 'Master of Design'), ('M.Sc', 'Master of Science'), ('Phd', 'PHD'), ('Others', 'Others')], default='B.Tech', max_length=256)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('MNC', 'Mathematics and Computing'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electronics and Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CL', 'Chemical Engineering'), ('EP', 'Engineering Physics'), ('CST', 'Chemical Science and Technology'), ('BT', 'Biotechnology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Design', 'Design'), ('Others', 'Others')], default='CSE', max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('experience', models.TextField()),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
                ('question3', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
