# Generated by Django 2.2.5 on 2020-06-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_portal', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnusProfile',
            fields=[
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('roll_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(max_length=20, null=True)),
                ('personal_email', models.CharField(max_length=50, null=True)),
                ('iitg_email', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('year_of_graduation', models.IntegerField(blank=True, null=True)),
                ('program', models.CharField(blank=True, choices=[('B.Tech', 'Bachelor of Technology'), ('B.Des', 'Bachelor of Design'), ('M.Tech', 'Master of Technology'), ('M.Des', 'Master of Design'), ('M.Sc', 'Master of Science'), ('Phd', 'PHD'), ('Others', 'Others')], max_length=10, null=True)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('MNC', 'Mathematics and Computing'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electronics and Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CL', 'Chemical Engineering'), ('EP', 'Engineering Physics'), ('CST', 'Chemical Science and Technology'), ('BT', 'Biotechnology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Design', 'Design'), ('Others', 'Others')], max_length=25, null=True)),
                ('current_address', models.CharField(max_length=200, null=True)),
                ('current_city', models.CharField(max_length=50, null=True)),
                ('current_country', models.CharField(blank=True, max_length=25, null=True)),
                ('pin', models.IntegerField(null=True)),
                ('permanent_address', models.CharField(max_length=200, null=True)),
                ('permanent_city', models.CharField(max_length=25, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=25, null=True)),
                ('permanent_pin', models.IntegerField(null=True)),
                ('google_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=250, null=True)),
                ('current_position', models.CharField(choices=[('scholar', 'Scholar'), ('job', 'Job'), ('startup', 'Startup/NGO'), ('other', 'Other')], max_length=150, null=True)),
                ('past_position_1', models.CharField(blank=True, max_length=150, null=True)),
                ('past_position_2', models.CharField(blank=True, max_length=150, null=True)),
                ('startup_link', models.CharField(blank=True, max_length=400, null=True)),
                ('position', models.TextField(null=True)),
                ('position_1', models.CharField(blank=True, max_length=30, null=True)),
                ('position_2', models.CharField(blank=True, max_length=30, null=True)),
                ('city_1', models.CharField(max_length=50, null=True)),
                ('city_2', models.CharField(blank=True, max_length=50, null=True)),
                ('city_3', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('company_1', models.CharField(blank=True, max_length=100, null=True)),
                ('company_2', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel', models.CharField(blank=True, choices=[('Barak', 'Barak'), ('Brahmaputra', 'Brahmaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ("Married Scholar's Hostel", "Married Scholar's Hostel"), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('Other', 'Other')], max_length=15, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('campus_involvements_1', models.CharField(blank=True, max_length=200, null=True)),
                ('campus_involvements_2', models.CharField(blank=True, max_length=200, null=True)),
                ('other_interests', models.TextField(blank=True, null=True)),
                ('about_you', models.TextField(blank=True, null=True)),
                ('your_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.Des', 'Bachelor of Design'), ('M.Tech', 'Master of Technology'), ('M.Des', 'Master of Design'), ('M.Sc', 'Master of Science'), ('Phd', 'PHD'), ('Others', 'Others')], max_length=40)),
                ('institute', models.CharField(max_length=100)),
                ('start_year', models.IntegerField(null=True)),
                ('pass_out_year', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('alumnus_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_portal.AlumnusProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(choices=[('scholar', 'Scholar'), ('job', 'Job'), ('startup', 'Startup/NGO'), ('other', 'Other')], max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('alumnus_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_portal.AlumnusProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='AlumniStory',
        ),
    ]
