# Generated by Django 2.2.5 on 2020-06-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_portal', '0004_auto_20200613_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnusprofile',
            old_name='other_interests',
            new_name='your_interests',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='campus_involvements_1',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='campus_involvements_2',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='permanent_city',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='permanent_country',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='permanent_pin',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='alumnusprofile',
            name='room_no',
        ),
        migrations.AlterField(
            model_name='education',
            name='alumnus_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='alumni_portal.AlumnusProfile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='alumnus_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='alumni_portal.AlumnusProfile'),
        ),
    ]
