# Generated by Django 2.2.5 on 2020-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_portal', '0005_auto_20200613_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnusprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
