# Generated by Django 2.2.5 on 2020-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_portal', '0006_alumnusprofile_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnusprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
