# Generated by Django 2.2.5 on 2020-06-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_portal', '0007_auto_20200615_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnusprofile',
            old_name='about_you',
            new_name='about_me',
        ),
        migrations.RenameField(
            model_name='alumnusprofile',
            old_name='your_interests',
            new_name='my_interests',
        ),
        migrations.RenameField(
            model_name='alumnusprofile',
            old_name='your_message',
            new_name='my_message',
        ),
    ]
