# Generated by Django 2.2.5 on 2020-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_portal', '0008_auto_20200615_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.AddField(
            model_name='job',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
