# Generated by Django 2.2.5 on 2020-06-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_portal', '0009_auto_20200616_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnusprofile',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
