# Generated by Django 2.2.5 on 2020-06-16 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_portal', '0011_alumnusprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnusprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
