# Generated by Django 3.0.7 on 2020-12-05 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('MNC', 'Mathematics and Computing'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electronics and Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CL', 'Chemical Engineering'), ('EP', 'Engineering Physics'), ('CST', 'Chemical Science and Technology'), ('BT', 'Biotechnology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Design', 'Design'), ('Others', 'Others')], default='CSE', max_length=50)),
                ('num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mnum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tnum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tmnum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('per', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mper', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DayTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayNum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mnum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=50, unique=True)),
                ('programs', models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.Des', 'Bachelor of Design'), ('M.Tech', 'Master of Technology'), ('M.Des', 'Master of Design'), ('M.Sc', 'Master of Science'), ('Phd', 'PHD'), ('Others', 'Others')], default='B.Tech', max_length=20)),
                ('day', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('company', models.CharField(blank=True, max_length=100)),
                ('placed', models.BooleanField(default=False)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('profile', models.CharField(blank=True, max_length=100)),
                ('slot', models.CharField(blank=True, choices=[('S1', 'Slot 1'), ('S2', 'Slot 2'), ('S3', 'Slot 3')], max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayNum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mnum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Branch')),
            ],
        ),
    ]
