# Generated by Django 3.0.7 on 2023-03-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_placed',
            field=models.CharField(choices=[('2023', '2023'), ('2022', '2022')], default='', max_length=4),
        ),
    ]
