# Generated by Django 2.2.2 on 2019-10-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Enter Branch', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='programs',
            field=models.CharField(choices=[('BTech', "Bachelor's of Technology"), ('BDes', 'Bachelor of Design'), ('MTech', 'Master of Technology'), ('MDes', 'Master of Design')], default='BTech', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='slot',
            field=models.CharField(blank=True, choices=[('S1', 'Slot 1'), ('S2', 'Slot 2'), ('S3', 'Slot 3')], max_length=2),
        ),
    ]
