# Generated by Django 2.2.2 on 2019-10-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191031_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='programs',
            field=models.CharField(choices=[('BTech', 'Bachelors of Technology'), ('BDes', 'Bachelor of Design'), ('MTech', 'Master of Technology'), ('MDes', 'Master of Design')], default='BTech', max_length=5),
        ),
    ]
