# Generated by Django 2.2.2 on 2019-10-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191031_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchNumberPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
