# Generated by Django 2.2.6 on 2019-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191031_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branchName',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('MNC', 'Mathematics and Computing'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electronics and Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CL', 'Chemical Engineering'), ('EP', 'Engineering Physics'), ('CST', 'Chemical Science and Technology'), ('BT', 'Biotechnology')], default='CSE', max_length=50),
        ),
    ]
