# Generated by Django 2.2.2 on 2019-11-08 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191106_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='day',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
