# Generated by Django 2.2.6 on 2019-11-14 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191108_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayNum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
