# Generated by Django 2.2.6 on 2020-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200101_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programs',
            field=models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.Des', 'Bachelor of Design'), ('M.Tech', 'Master of Technology'), ('M.Des', 'Master of Design')], default='BTech', max_length=5),
        ),
    ]
