# Generated by Django 2.2.2 on 2020-01-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200105_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programs',
            field=models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.Des', 'Bachelor of Design'), ('M.Tech', 'Master of Technology'), ('M.Des', 'Master of Design')], default='B.Tech', max_length=5),
        ),
    ]
