# Generated by Django 2.2.6 on 2020-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200108_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='mper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='branch',
            name='per',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
